# When set to false, ignores files with "GENERATED" header, similar to golint
ignoreGeneratedHeader = true

# Sets the default severity to "warning"
severity = "warning"

# Sets the error code for failures with severity "error"
errorCode = 1

# Sets the error code for failures with severity "warning"
warningCode = 0

enableAllRules = true

# Disabled rules
[rule.blank-imports]
    Disabled = true
[rule.empty-lines]
    Disabled = true
[rule.file-header]
    Disabled = true
[rule.max-public-structs]
    Disabled = true
[rule.line-length-limit]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.banned-characters]
    Disabled = true

# Rule tuning
[rule.add-constant]
    Arguments = [{allowInts="-1,0,1,2",allowStrs="\"\"",allowFloats="0.0,1.0",ignoreFuncs="os\\.*,fmt\\.*"}]

[rule.argument-limit]
    Arguments = [5]
[rule.cyclomatic]
    Arguments = [20]
[rule.cognitive-complexity]
    Arguments = [20]
[rule.function-result-limit]
    Arguments = [3]
[rule.error-strings]
    Arguments = ["mypackage.Error"]

[rule.var-naming]
  Arguments = [["ID","DI","ACL", "UID","EOF","HTTP","JSON","API"], [] , [{upperCaseConst=true}]]

[rule.unhandled-error]
  Arguments =[
    "fmt.Print", 
    "fmt.Printf",
    "fmt.Println", 
    "strings.Builder.WriteString",
    "strings.Builder.WriteByte",
    ]